bitwarden/mcp-server

.github/workflows/scan.yml

Noticed while reviewing new scan results.
Provides the source and test paths to Sonar like with do with other TypeScript projects.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

Provide source and test paths for Sonar scan

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
package.json

[BRE-1011](https://bitwarden.atlassian.net/browse/BRE-1011)
Updating release and publish workflows
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …

[BRE-1011] Update release/publish workflows

---

README.md

Based on the release of the NPM package.
Explains the preferred tool-based option to directly configure the NPM package vs. pulling down the repo.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …

Document new NPM package

---

.github/workflows/publish.yml
.github/workflows/release.yml
package.json

[BRE-1011](https://bitwarden.atlassian.net/browse/BRE-1011)
Setting version to 2025.7.0
Fixing GitHub auth
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …

BRE-1011 Updating version

---

package-lock.json
package.json
src/index.ts

Based on a few version bump PRs of the dependencies, most importantly the MCP SDK.
Prepares for a `.1` release.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …

Bump version to 2025.7.1

---

package-lock.json
package.json
src/index.ts

Release for #34.
New patch release.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for …

Bump version to 2025.7.2

---

.github/workflows/scan.yml

Noticed while reviewing Sonar results.
The `tests/` folder should be marked in Sonar as a test folder.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …

Mark tests for Sonar

---

.github/workflows/build.yml

https://bitwarden.atlassian.net/browse/BRE-1013
Fix `build` from hanging during `cosign` steps during non-interactive mode.
* Include sufficient permissions to avoid user interaction.
- 🤔 (`:thinking:`) or …

BRE-1013 fix: required permissions

---

.github/workflows/publish.yml
.github/workflows/release.yml

https://bitwarden.atlassian.net/browse/BRE-1013
Finalize changes to allow release and publish stages to push to GHCR.
* uncomment push operation from release
* uncomment push operation from publish
* fix pull operation; permissions
- ❓ …

BRE-1013 cd: push to ghcr

---

.github/workflows/publish.yml

https://bitwarden.atlassian.net/browse/BRE-1013
Resolve generic failures during publish stage.
* fix syntax error caused by typo
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

BRE-1013 cd: syntax error

---

Dockerfile

Reviewing security findings.
Adds a rather obtuse healthcheck to meet security scanner checks. Since this is using `stdio` we can send a JSON-RPC ping command and expect it back.
- 🤔 (`:thinking:`) or 💭 …

Add Docker healthcheck

---

Dockerfile

https://bitwarden.atlassian.net/browse/BRE-1013
Include `build` to build stage to resolve missing module from final stage
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …

BRE-1013 fix: Dockerfile

---

Dockerfile

Testing the latest release.
Moves a few things around to be more like the normal `Dockerfile` structure I see around with MCP servers with the added benefit of distroless.
- 🤔 (`:thinking:`) or 💭 …

Restructure Docker image

---

.github/workflows/publish.yml

[BRE-1076](https://bitwarden.atlassian.net/browse/BRE-1076)
Use OIDC to npm publish<br/>
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …

[BRE-1076] Use OIDC to npm publish

---

package-lock.json
package.json
src/index.ts

Release preparation.
Releasing the new API functionality.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …

Bump version to 2025.9.0

---

package-lock.json
package.json
src/index.ts
src/utils/api.ts

Release preparation.
Releasing the new CLI functionality and overall fixes.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …

Bump version to 2025.10.0

---

CLAUDE.md
README.md
src/handlers/cli.ts
src/index.ts
src/schemas/cli.ts
src/tools/cli.ts
src/utils/security.ts
tests/cli-commands.spec.ts

Add support for org admin device approvals through CLI tools.

add support for device approval commands

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

https://bitwarden.atlassian.net/browse/VULN-285
Perform cleanup of existing workflows to be in compliance with Zizmor and bwwl.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

Clean up workflow files from Zizmor output

---

.github/workflows/build.yml

Continuation of #89
Change the array logic to work with cosign properly. Also address the array usage in the next step of the workflow.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

Fix Cosign arguments part 2

---

CLAUDE.md
README.md
src/handlers/cli.ts
src/index.ts
src/schemas/cli.ts
src/tools/cli.ts
tests/cli-commands.spec.ts
tests/core.spec.ts
tests/validation.spec.ts

Add CLI restore command as a new tool.

add restore tool
